// Camp schedule data for all sessions and weeks
export const campSchedules = {
  session1: [
    {
      week: "Week 1",
      days: [
        "Sunday",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
      ],
      dates: [
        "6/14/2026",
        "6/15/2026",
        "6/16/2026",
        "6/17/2026",
        "6/18/2026",
        "6/19/2026",
        "6/20/2026",
      ],
      times: [
        "08:00–08:30 AM",
        "08:30–09:00 AM",
        "09:00–10:10 AM",
        "10:10–10:30 AM",
        "10:30–12:00 PM",
        "12:00–01:00 PM",
        "01:00–02:30 PM",
        "02:30–05:30 PM",
        "05:30–06:00 PM",
        "06:00–07:30 PM",
        "07:30–09:00 PM",
        "09:00–10:00 PM",
        "10:00 PM",
      ],
      schedule: [
        [
          "-",
          "Wake up",
          "Wake up",
          "Wake up",
          "Wake up",
          "Wake up",
          "Wake up",
        ],
        [
          "-",
          "Breakfast",
          "Breakfast",
          "Breakfast",
          "Breakfast",
          "Breakfast",
          "Breakfast",
        ],
        [
          "-",
          "Camp Opening Ceremony",
          "S2: Financial Market Fundamentals",
          "S4: Bottom-up Equity Research & Top-down Equity Research",
          "S5: Financial Statement",
          "S6: Financial Analysis",
          "Boston Trip: Harvard University, MIT, etc. City Tour",
        ],
        [
          "-",
          "Class Break",
          "Class Break",
          "Class Break",
          "Class Break",
          "Class Break",
          "Boston Trip: Harvard University, MIT, etc. City Tour",
        ],
        [
          "-",
          "S1: Money Talk Overview",
          "S3: Macro Economics Sectors & Industries",
          "S4: Bottom-up Equity Research & Top-down Equity Research",
          "S6: Financial Analysis",
          "S7: Quantitative Analysis/Information Sources",
          "Boston Trip: Harvard University, MIT, etc. City Tour",
        ],
        [
          "-",
          "Lunch",
          "Lunch",
          "Lunch",
          "Lunch",
          "Lunch",
          "Boston Trip: Harvard University, MIT, etc. City Tour",
        ],
        [
          "Arriving: Check-in, dorm setup, meet new friends",
          "Setup Million dollar Stock Competition",
          "Stock trading and Market watch",
          "Stock Trading and Market Watch",
          "Stock Trading and Market Watch",
          "AI Application Class",
          "Boston Trip: Harvard University, MIT, etc. City Tour",
        ],
        [
          "Arriving: Check-in, dorm setup, meet new friends",
          "Groceries shopping",
          "Sports/Workshop 3:00-5:00PM",
          "Sports/Workshop 3:00-5:00PM",
          "Sports/Workshop 3:00-5:00PM",
          "Team Activities / Group Project",
          "Boston Trip: Harvard University, MIT, etc. City Tour",
        ],
        [
          "Arriving: Check-in, dorm setup, meet new friends",
          "Personal Hygiene",
          "Personal Hygiene",
          "Personal Hygiene",
          "Personal Hygiene",
          "Personal Hygiene",
          "Personal Hygiene",
        ],
        [
          "Dinner",
          "Dinner",
          "Dinner",
          "Dinner",
          "Dinner",
          "BBQ",
          "Dinner",
        ],
        [
          "1. Icebreak activities\n2. Student meeting (Summer camp rules, Cell Phone Policy)",
          "Talent show briefing and board nomination/selection",
          "Movie Night",
          "College Application Overview and Experience Sharing",
          "Sports Night",
          "Bon Fire Smore",
          "Movie Night",
        ],
        [
          "1. Icebreak activities\n2. Student meeting (Summer camp rules, Cell Phone Policy)",
          "Free Time at dorm",
          "Free Time at dorm",
          "Free Time at dorm",
          "Free Time at dorm",
          "Free Time at dorm",
          "Free Time at dorm",
        ],
        [
          "Get ready for bed",
          "Get ready for bed",
          "Get ready for bed",
          "Get ready for bed",
          "Get ready for bed",
          "Get ready for bed",
          "Get ready for bed",
        ],
      ],
    },
    {
      week: "Week 2",
      days: [
        "Sunday",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
      ],
      dates: [
        "6/21/2026",
        "6/22/2026",
        "6/23/2026",
        "6/24/2026",
        "6/25/2026",
        "6/26/2026",
        "6/27/2026",
      ],
      times: [
        "08:00–08:30 AM",
        "08:30–09:00 AM",
        "09:00–10:10 AM",
        "10:10–10:30 AM",
        "10:30–12:00 PM",
        "12:00–01:00 PM",
        "01:00–02:30 PM",
        "02:30–05:30 PM",
        "05:30–06:00 PM",
        "06:00–07:30 PM",
        "07:30–09:00 PM",
        "09:00–10:00 PM",
        "10:00 PM",
      ],
      schedule: [
        [
          "Good Morning :)",
          "Wake up",
          "Wake up",
          "Wake up",
          "Wake up",
          "Wake up",
          "Good Morning :)",
        ],
        [
          "Good Morning :)",
          "Breakfast",
          "Breakfast",
          "Breakfast",
          "Breakfast",
          "Breakfast",
          "Good Morning :)",
        ],
        [
          "Good Morning :)",
          "S8: Financial Modeling",
          "S9: Stock Valuation",
          "S10: Investment Strategies and Mainstream Investment Styles",
          "S11: Risk & Return Risk Management",
          "Final Investment Competition",
          "Good Morning :)",
        ],
        [
          "Brunch",
          "Class Break",
          "Class Break",
          "Class Break",
          "Class Break",
          "Class Break",
          "Departure",
        ],
        [
          "AI seminar",
          "S8: Financial Modeling",
          "S9: Stock Valuation",
          "S11: Risk & Return Risk Management",
          "S12: Portfolio Management",
          "Final Investment Competition",
          "Departure",
        ],
        [
          "Lunch",
          "Lunch",
          "Lunch",
          "Lunch",
          "Lunch",
          "Lunch",
          "Departure",
        ],
        [
          "Springfield tour",
          "Stock trading and Market watch",
          "Stock trading and Market watch",
          "Stock trading and Market watch",
          "Investment project—teamwork",
          "Award Ceremony Millions Dollar Cup Top 5 Leadership Award Counselor Award Final Investment Competition Award",
          "Departure",
        ],
        [
          "Springfield tour",
          "AI, VR & Innovation Lab",
          "Team Discussion",
          "Sports/Workshop 3:00-5:00PM",
          "Team Practice for Final Presentation",
          "Award Ceremony Millions Dollar Cup Top 5 Leadership Award Counselor Award Final Investment Competition Award",
          "Departure",
        ],
        [
          "Personal Hygiene",
          "Personal Hygiene",
          "Personal Hygiene",
          "Personal Hygiene",
          "Personal Hygiene",
          "Personal Hygiene",
          "-",
        ],
        [
          "Dinner",
          "Dinner",
          "Dinner",
          "Dinner",
          "Dinner",
          "Camp Formal SCISS Red Carpet Gala Night",
          "-",
        ],
        [
          "Movie Night",
          "Team Discussion",
          "Talent Show Rehearsal",
          "Talent Show",
          "Investment project—teamwork",
          "Camp Formal SCISS Red Carpet Gala Night",
          "-",
        ],
        [
          "Free Time at dorm",
          "Free Time at dorm",
          "Free Time at dorm",
          "Talent Show",
          "Free Time at dorm",
          "Camp Formal SCISS Red Carpet Gala Night",
          "-",
        ],
        [
          "Get ready for bed",
          "Get ready for bed",
          "Get ready for bed",
          "Get ready for bed",
          "Get ready for bed",
          "Get ready for bed",
          "-",
        ],
      ],
    },
  ],
  // session2: [] // Placeholder for future session 2
};
