import React from "react";
// Camp schedule data for all sessions and weeks
export const campSchedules = {
  session1: [
    {
      week: "Week 1",
      days: [
        "Sunday",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
      ],
      dates: [
        "6/29/2025",
        "6/30/2025",
        "7/1/2025",
        "7/2/2025",
        "7/3/2025",
        "7/4/2025",
        "7/5/2025",
      ],
      times: [
        "09:00–10:10 AM",
        "10:10–10:30 AM",
        "10:30–12:00 AM",
        "01:00–02:30 PM",
        "02:30–05:30 PM",
        "07:30–09:00 PM",
      ],
      schedule: [
        [
          "-",
          "Camp Opening Ceremony\nAngelene Huang SCA President\nAnthony Lorenzano TD Bank\nTony Zhou HedgeFund MD",
          "S2: Financial Market Fundamentals",
          "S3: Macro Economics Sectors & Industries",
          "S4: Bottom-up Equity Research & Top-down Equity Research",
          "S5: Financial Statement",
          "-",
        ],
        [
          "-",
          "Class Break",
          "Class Break",
          "Class Break",
          "Class Break",
          "Class Break",
          "-",
        ],
        [
          "-",
          "S1: Money Talk Overview",
          "S2: Financial Market Fundamentals",
          "S3: Macro Economics Sectors & Industries",
          "S4: Bottom-up Equity Research & Top-down Equity Research",
          "S5: Financial Statement",
          "Boston Trip: Harvard University, MIT, etc. City Tour",
        ],
        [
          "-",
          "Setup Million dollar Stock Competition",
          "Stock trading and Market watch / Art Workshop",
          "Stock Trading and Market Watch / Art Workshop",
          "AI Application Class",
          "AI Application Class",
          "-",
        ],
        [
          "-",
          "Option 1: Groceries @ Target\nOption 2: Basketball Camp 3:00–4:00PM",
          "Option 1: Rowing 3:00–5:00PM\nOption 2: Basketball Camp 3:00–4:00PM",
          "Option 1: Springfield Museums 2:30–5:00PM\nOption 2: Golf 2:30–5:00PM",
          "Kung Fu Workshop 3:00–4:00PM",
          "Team Activities / Group Project\nOption 2: Basketball Camp 3:00–4:00PM",
          "-",
        ],
        [
          "1. Icebreak activities\n2. Student meeting (Summer camp rules, Cell Phone Policy)",
          "Movie Night: Homless to Harvard",
          "Guest Speaker: Impact Investment Satya S. Tripathi CEO of Global Alliance Former United Nation Sec General",
          "College Application Overview and Experience Sharing by our Interns",
          "Baseball Game: Westfield Starfires 6:30–9PM",
          "Star Spangled Springfield (Fireworks @ 9:30PM)",
          "Movie Night: Big Shorts",
        ],
      ],
    },
    {
      week: "Week 2",
      days: [
        "Sunday",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
      ],
      dates: [
        "7/6/2025",
        "7/7/2025",
        "7/8/2025",
        "7/9/2025",
        "7/10/2025",
        "7/11/2025",
        "7/12/2025",
      ],
      times: [
        "09:00–10:10 AM",
        "10:10–10:30 AM",
        "10:30–12:00 AM",
        "01:00–02:30 PM",
        "02:30–05:30 PM",
        "07:30–09:00 PM",
      ],
      schedule: [
        [
          "Springfield Armory National Historic Site 9:30AM–4PM",
          "S6: Financial Analysis",
          "S7: Quantitative Analysis/Information Sources",
          "S8: Financial Modeling",
          "S8: Financial Modeling",
          "S9: Stock Valuation",
          "-",
        ],
        [
          "Breakfast",
          "Class Break",
          "Class Break",
          "Class Break",
          "Class Break",
          "Class Break",
          "Breakfast",
        ],
        [
          "Basketball Hall of Fame 10AM–4PM",
          "S6: Financial Analysis",
          "S7: Quantitative Analysis/Information Sources",
          "S8: Financial Modeling",
          "S9: Stock Valuation",
          "S9: Stock Valuation",
          "Six Flags New England Amusement Park 10:30AM–5:30PM",
        ],
        [
          "-",
          "Stock trading and Market watch / Art Workshop",
          "Stock trading and Market watch / Art Workshop",
          "Stock trading and Market watch / Art Workshop",
          "Yale Trip (Box Lunch)",
          "AI Application Class",
          "-",
        ],
        [
          "-",
          "AI, VR & Innovation Lab with Professor Li @ Western New England University 2:30 PM – 5:30 PM",
          "Option 1: Forest Park Farmer's Market Nature Walk & Zoo\nOption 2: Rowing 3:00–5:00PM",
          "Option 1: ROWING 3:00–5:00PM\nOption 2: Golf 2:30–5:00PM",
          "-",
          "Option 1: Morcay's Farm 2:30–5:00PM\nOption 2: Golf 2:30–5:00PM",
          "-",
        ],
        [
          "Movie Night: Good Will Hunting",
          "Team Activities / Group Project/Fitness Center",
          "Investment Speaker: Daytrade Tech Strategy Mr. Shao (Zoom)",
          "College Application for Senior/ACT SAT Mock",
          "Team Activities / Group Project/Fitness Center",
          "Bon Fire Smore",
          "Movie Night: The Banker",
        ],
      ],
    },
    {
      week: "Week 3",
      days: [
        "Sunday",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
      ],
      dates: [
        "7/13/2025",
        "7/14/2025",
        "7/15/2025",
        "7/16/2025",
        "7/17/2025",
        "7/18/2025",
        "7/19/2025",
      ],
      times: [
        "09:00–10:10 AM",
        "10:10–10:30 AM",
        "10:30–12:00 AM",
        "01:00–02:30 PM",
        "02:30–05:30 PM",
        "07:30–09:00 PM",
      ],
      schedule: [
        [
          "Brown University Self Guided Tour in Rhode Island & Beach Day @ Misquamicut State Beach",
          "S10: Investment Strategies and Mainstream Investment Styles",
          "S11: Risk & Return Risk Management",
          "S12: Portfolio Management",
          "Team Practice for Final Presentation",
          "Guest Lecture: Future and Derivatives Tony Zhou HedgeFund MD",
          "-",
        ],
        [
          "-",
          "Class Break",
          "Class Break",
          "Class Break",
          "Class Break",
          "Prepare for Final Presentation",
          "-",
        ],
        [
          "-",
          "S10: Investment Strategies and Mainstream Investment Styles",
          "S11: Risk & Return Risk Management",
          "S12: Portfolio Management",
          "Investment Speaker: Risk Management Ms. Liu Head of Investment (Zoom)",
          "Final Investment Competition",
          "Departure",
        ],
        [
          "-",
          "AI application Class",
          "Stock trading and Market watch / Art Workshop",
          "Stock trading and Market watch / Art Workshop",
          "Stock Trading and Market Watch (End of Competition)",
          "Award Ceremony Millions Dollar Cup Top 5 Leadership Award Counselor Award Final Investment Competition Award",
          "-",
        ],
        [
          "-",
          "Option 1: Rowing 3:00–5:00PM\nOption 2: Basketball Camp 3:00–4:00PM",
          "Pollyanna @ Majestic Theatre 1",
          "UMASS Amherst Beneski Museum of Natural History Mead Art Museum\nOption 1: Golf 2:30–5:00PM\nOption 2: Basketball Camp 3:00–4:00PM",
          "Option 1: Golf 2:30–5:00PM\nOption 2: Basketball Camp 3:00–4:00PM",
          "Camp Formal SCISS Red Carpet Gala Night Chateau Douillet 400 Maple Street",
          "-",
        ],
        [
          "Talent Show Practice/Preparation",
          "Talent Show Practice/Final Preparation",
          "Talent Show Practice/Final Preparation",
          "Talent Show",
          "Team Practice for Final Presentation",
          "-",
          "-",
        ],
      ],
    },
  ],
  // session2: [] // Placeholder for future session 2
};
